/*
 * $Id$
 *
 * Copyright (c) 2015 Sogou.com. All Rights Reserved.
 */
package leetcode;

//--------------------- Change Logs----------------------
//@author wangwenlong Initial Created at 2016年8月29日;
//-------------------------------------------------------
public class FindtheDifference {
  /*
  Given two strings s and t which consist of only lowercase letters.  
  String t is generated by random shuffling string s and then add one more letter at a random position.  
  Find the letter that was added in t.
  
  Example:  
  Input:
  s = "abcd"
  t = "abcde"
  
  Output:e  
  Explanation:'e' is the letter that was added.
  */

  public char findTheDifference(String s, String t) {
    int[] counts = new int[128];
    s.chars().forEach(c -> counts[c]++);
    return (char) t.chars().filter(c -> --counts[c] < 0).findFirst().getAsInt();
  }

}
